language: python

sudo: enabled

services: mysql

python:
  - "3.6"
  - "3.7"
  - "3.7-dev"

env:
  global:
    - TRAVIS=true

branches:
  only:
    - f-20190525-starrier-init

install:
  - pip install -r requirements.txt

script:
  - make test
  - python manage.py test

notifications:
  email:
    recipients:
      - starrier@starrier.org
    on_success: change
    on_failure: always
  slack:
    rooms:
      - ${SLACK_ACCOUNT}:${SLACK_TOKEN}#general
      - ${SLACK_ACCOUNT}:${SLACK_TOKEN}#random
    on_success: change
    on_failure: always
    on_pull_requests: true