language: python

sudo: enabled

services: mysql

python:
  - "3.7.3"

env:
  global:
    - TRAVIS=true

before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS little;'
  - mv config.example.json configs.json

branches:
  only:
    - f-20190525-starrier-init

install:
  - pip install -r requirements.txt

script:
  - make test
  - python manage.py test

notifications:
  recipients:
    - starrier@starrier.org
  on_success: change
  on_failure: always
  irc:
    channels:
      - ""
    on_success: change
    on_failure: always
