language: python

sudo: enabled

services: mysql

python:
  - "3.7-dev"

env:
  global:
    - TRAVIS=true

branches:
  only:
    - f-20190525-starrier-init

install:
  - pip install -r requirements.txt

script:
  - python manage.py

notifications:
  email:
    recipients:
      - ${EMAIL}
    on_success: change
    on_failure: always
  slack:
    rooms:
      - ${SLACK_ACCOUNT}:${SLACK_TRAVIS_TOKEN}#travis-ci
      - ${SLACK_ACCOUNT}:${SLACK_TOKEN}#general
      - ${SLACK_ACCOUNT}:${SLACK_TOKEN}#random
    on_success: change
    on_failure: always